server:
  port: 8084
  servlet:
    context-path: /camunda-api

spring:
  profiles:
    active: druid,dev
  redis:
    schema: workflow
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    # password: 12345
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

management:
  endpoints:
    web:
      exposure:
        include: "shutdown" # 允许所有端点被暴露，也可以根据需求指定具体的端点，比如 health, info 等
  endpoint:
    shutdown:
      enabled: true